services:
  postgres:
    image: postgres:16.1
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - iaton-network

volumes:
  postgres_data:

networks:
  iaton-network:
    name: iaton-network
    driver: bridge