apiVersion: v1
kind: ConfigMap
metadata:
  name: api--customer-cm
  namespace: iaton
data:
  SPRING_PROFILES_ACTIVE: "dev,jsonlog,logbook"
  API_KEY_SECURITY: "MmUyYTVjNGQtODViNy00M2Q2LWEwN2ItNTZlYTUzNGM2YTRh"
  KAFKA_BOOTSTRAP_SERVER: "kafka-broker.ns-infra.svc.cluster.local:9092"
  KAFKA_SCHEMA_REGISTRY: "http://schema-registry.ns-infra.svc.cluster.local:8081"
  POSTGRES_DATABASE: "db"
  POSTGRES_HOST: "postgres.ns-infra.svc.cluster.local"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USERNAME: "postgres"
  SPRING_JPA_SHOW_SQL: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.ns-infra.svc.cluster.local:4318/v1/traces"