apiVersion: v1
kind: Service
metadata: 
  name: api--customer-user
  namespace: iaquant
spec:
  type: ClusterIP
  selector:
      app: api--customer-user
  ports:
    - port: 5000
      name: http-5000
      protocol: TCP
      targetPort: 5000
    - port: 9190
      name: http-prometheus
      protocol: TCP
      targetPort: 9190