spring:
  application:
    name: api--customer-user
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mapping: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  main:
    banner-mode: "OFF"
    retry:
      max-attempts: 5000
      initial-interval: 1500
      multiplier: 1.5
      compatibility-verifier:
        enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DATABASE:db}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}

server:
  max-http-request-size: 60000
  shutdown: graceful
  servlet:
    context-path: /api--customer-user
  port: 5000

info:
  app:
    name: "api--customer-user"
    version: "0.0.1-SNAPSHOT"
    description: "Demo project for Spring Boot "
    base-package: "br.com.iaquant.api.customer"

management:
  server:
    port: 9090
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: diskSpace
  tracing:
    sampling:
      probability: 0.1

